import { Geist, Geist_Mono } from "next/font/google";
import ClientLayoutWrapper from "./layout-provider";
import "./globals.css";
import "../styles/tailwind.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "JobEazy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientLayoutWrapper>
           {children}
        </ClientLayoutWrapper>
      </body>
    </html>
  );
}
